name: flutter_sleeping_hours_slider_example
description: Demonstrates how to use the flutter_sleeping_hours_slider plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_sleeping_hours_slider:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/